[2024-07-14T18:50:01.853+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T18:50:01.865+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [queued]>
[2024-07-14T18:50:01.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [queued]>
[2024-07-14T18:50:01.869+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T18:50:01.876+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 18:40:00+00:00
[2024-07-14T18:50:01.881+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T18:50:01.884+0000] {standard_task_runner.py:63} INFO - Started process 8127 to run task
[2024-07-14T18:50:01.883+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T18:40:00+00:00', '--job-id', '2416', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp3qf37o5i']
[2024-07-14T18:50:01.885+0000] {standard_task_runner.py:91} INFO - Job 2416: Subtask save_and_flush_task
[2024-07-14T18:50:01.926+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [running]> on host d537c34a4880
[2024-07-14T18:50:01.977+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T18:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T18:40:00+00:00'
[2024-07-14T18:50:01.979+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T18:50:01.980+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T18:50:01.980+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T18:50:01.986+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T18:40:00+00:00, execution_date=20240714T184000, start_date=20240714T185001, end_date=20240714T185001
[2024-07-14T18:50:02.024+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T18:50:02.034+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T18:50:02.035+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:35:38.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:38.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [queued]>
[2024-07-14T20:35:38.545+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [queued]>
[2024-07-14T20:35:38.546+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:38.552+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 18:40:00+00:00
[2024-07-14T20:35:38.555+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:38.556+0000] {standard_task_runner.py:63} INFO - Started process 2305 to run task
[2024-07-14T20:35:38.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T18:40:00+00:00', '--job-id', '1046', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpee71d00h']
[2024-07-14T20:35:38.557+0000] {standard_task_runner.py:91} INFO - Job 1046: Subtask save_and_flush_task
[2024-07-14T20:35:38.584+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:38.630+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T18:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T18:40:00+00:00'
[2024-07-14T20:35:38.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:38.637+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:38.637+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:38.643+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T18:40:00+00:00, execution_date=20240714T184000, start_date=20240714T203538, end_date=20240714T203538
[2024-07-14T20:35:38.654+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:38.663+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:38.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:37:53.972+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:37:54.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [queued]>
[2024-07-15T06:37:54.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [queued]>
[2024-07-15T06:37:54.014+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:37:54.034+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 18:40:00+00:00
[2024-07-15T06:37:54.039+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4011) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:37:54.040+0000] {standard_task_runner.py:63} INFO - Started process 4022 to run task
[2024-07-15T06:37:54.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T18:40:00+00:00', '--job-id', '685', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp92sngksd']
[2024-07-15T06:37:54.041+0000] {standard_task_runner.py:91} INFO - Job 685: Subtask save_and_flush_task
[2024-07-15T06:37:54.091+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T18:40:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:37:54.197+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T18:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T18:40:00+00:00'
[2024-07-15T06:37:54.200+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:37:54.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:37:54.214+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:37:54.221+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T18:40:00+00:00, execution_date=20240714T184000, start_date=20240715T063754, end_date=20240715T063754
[2024-07-15T06:37:54.274+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 685 for task save_and_flush_task ('module' object is not callable; 4022)
[2024-07-15T06:37:54.310+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:37:54.331+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
