[2024-07-14T07:14:21.486+0000] {processor.py:161} INFO - Started process (PID=48008) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:14:21.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:14:21.488+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:14:21.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:14:21.495+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:14:21.494+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:14:21.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:14:21.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.025 seconds
[2024-07-14T07:14:31.914+0000] {processor.py:161} INFO - Started process (PID=48020) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:14:31.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:14:31.915+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:14:31.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:14:31.922+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:14:31.921+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:14:31.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:14:31.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.022 seconds
[2024-07-14T07:15:02.399+0000] {processor.py:161} INFO - Started process (PID=48068) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:15:02.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:15:02.404+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:15:02.404+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:15:02.414+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:15:02.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:15:02.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:15:02.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.040 seconds
[2024-07-14T07:15:17.037+0000] {processor.py:161} INFO - Started process (PID=48127) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:15:17.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:15:17.041+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:15:17.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:15:17.049+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:15:17.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:15:17.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:15:17.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.031 seconds
[2024-07-14T07:15:47.948+0000] {processor.py:161} INFO - Started process (PID=48186) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:15:47.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:15:47.952+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:15:47.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:15:47.960+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:15:47.959+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:15:47.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:15:47.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.037 seconds
[2024-07-14T07:16:18.872+0000] {processor.py:161} INFO - Started process (PID=48245) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:16:18.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:16:18.876+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:16:18.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:16:18.885+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:16:18.883+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:16:18.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:16:18.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.040 seconds
[2024-07-14T07:16:23.933+0000] {processor.py:161} INFO - Started process (PID=48246) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:16:23.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:16:23.936+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:16:23.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:16:23.948+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:16:23.946+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:16:23.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:16:23.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.038 seconds
[2024-07-14T07:16:29.003+0000] {processor.py:161} INFO - Started process (PID=48247) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:16:29.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:16:29.006+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:16:29.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:16:29.015+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:16:29.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:16:29.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:16:29.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.033 seconds
[2024-07-14T07:17:00.007+0000] {processor.py:161} INFO - Started process (PID=48306) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:17:00.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:17:00.013+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:17:00.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:17:00.029+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:17:00.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:17:00.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:17:00.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.057 seconds
[2024-07-14T07:17:30.101+0000] {processor.py:161} INFO - Started process (PID=48365) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:17:30.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:17:30.106+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:17:30.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:17:30.116+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:17:30.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:17:30.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:17:30.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.045 seconds
[2024-07-14T07:18:01.074+0000] {processor.py:161} INFO - Started process (PID=48424) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:18:01.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:18:01.077+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:18:01.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:18:01.086+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:18:01.084+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:18:01.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:18:01.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.038 seconds
[2024-07-14T07:18:31.897+0000] {processor.py:161} INFO - Started process (PID=48483) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:18:31.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:18:31.900+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:18:31.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:18:31.909+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:18:31.907+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:18:31.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:18:31.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.041 seconds
[2024-07-14T07:19:02.774+0000] {processor.py:161} INFO - Started process (PID=48542) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:19:02.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:19:02.777+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:19:02.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:19:02.786+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:19:02.784+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:19:02.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:19:02.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.039 seconds
[2024-07-14T07:19:33.680+0000] {processor.py:161} INFO - Started process (PID=48601) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:19:33.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:19:33.683+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:19:33.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:19:33.691+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:19:33.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:19:33.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:19:33.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.030 seconds
[2024-07-14T07:20:04.558+0000] {processor.py:161} INFO - Started process (PID=48660) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:20:04.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:20:04.560+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:20:04.560+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:20:04.566+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:20:04.565+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:20:04.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:20:04.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.027 seconds
[2024-07-14T07:20:35.418+0000] {processor.py:161} INFO - Started process (PID=48719) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:20:35.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:20:35.421+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:20:35.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:20:35.430+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:20:35.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:20:35.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:20:35.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.031 seconds
[2024-07-14T07:21:06.265+0000] {processor.py:161} INFO - Started process (PID=48778) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:21:06.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:21:06.268+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:21:06.268+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:21:06.275+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:21:06.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:21:06.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:21:06.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.037 seconds
[2024-07-14T07:21:36.989+0000] {processor.py:161} INFO - Started process (PID=48837) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:21:36.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:21:36.992+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:21:36.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:21:37.006+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:21:37.004+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:21:37.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:21:37.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.031 seconds
[2024-07-14T07:22:07.774+0000] {processor.py:161} INFO - Started process (PID=48896) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:22:07.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:22:07.780+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:22:07.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:22:07.789+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:22:07.787+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:22:07.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:22:07.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.039 seconds
[2024-07-14T07:22:38.731+0000] {processor.py:161} INFO - Started process (PID=48955) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:22:38.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:22:38.738+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:22:38.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:22:38.748+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:22:38.746+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:22:38.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:22:38.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.069 seconds
[2024-07-14T07:23:09.578+0000] {processor.py:161} INFO - Started process (PID=49013) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:23:09.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:23:09.579+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:23:09.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:23:09.583+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:23:09.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:23:09.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:23:09.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.021 seconds
[2024-07-14T07:23:40.464+0000] {processor.py:161} INFO - Started process (PID=49072) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:23:40.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:23:40.466+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:23:40.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:23:40.472+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:23:40.470+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:23:40.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:23:40.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.027 seconds
[2024-07-14T07:24:11.189+0000] {processor.py:161} INFO - Started process (PID=49130) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:24:11.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:24:11.192+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:24:11.192+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:24:11.198+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:24:11.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:24:11.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:24:11.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.028 seconds
[2024-07-14T07:24:42.066+0000] {processor.py:161} INFO - Started process (PID=49189) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:24:42.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:24:42.072+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:24:42.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:24:42.081+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:24:42.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:24:42.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:24:42.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.040 seconds
[2024-07-14T07:25:13.000+0000] {processor.py:161} INFO - Started process (PID=49248) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:25:13.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:25:13.003+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:25:13.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:25:13.010+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:25:13.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:25:13.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:25:13.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.040 seconds
[2024-07-14T07:25:43.916+0000] {processor.py:161} INFO - Started process (PID=49307) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:25:43.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:25:43.918+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:25:43.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:25:43.924+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:25:43.923+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:25:43.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:25:43.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.027 seconds
[2024-07-14T07:26:14.103+0000] {processor.py:161} INFO - Started process (PID=49366) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:26:14.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:26:14.106+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:26:14.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:26:14.113+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:26:14.112+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:26:14.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:26:14.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.037 seconds
[2024-07-14T07:26:44.954+0000] {processor.py:161} INFO - Started process (PID=49425) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:26:44.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:26:44.958+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:26:44.957+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:26:44.965+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:26:44.963+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:26:44.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:26:44.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.033 seconds
[2024-07-14T07:27:15.864+0000] {processor.py:161} INFO - Started process (PID=49484) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:27:15.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:27:15.869+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:27:15.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:27:15.878+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:27:15.876+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:27:15.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:27:15.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.046 seconds
[2024-07-14T07:27:46.679+0000] {processor.py:161} INFO - Started process (PID=49543) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:27:46.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:27:46.683+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:27:46.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:27:46.691+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:27:46.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:27:46.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:27:46.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.039 seconds
[2024-07-14T07:28:16.799+0000] {processor.py:161} INFO - Started process (PID=49602) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:28:16.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:28:16.804+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:28:16.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:28:16.813+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:28:16.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:28:16.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:28:16.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.046 seconds
[2024-07-14T07:28:46.979+0000] {processor.py:161} INFO - Started process (PID=49661) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:28:46.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:28:46.984+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:28:46.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:28:46.991+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:28:46.990+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:28:46.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:28:47.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.039 seconds
[2024-07-14T07:29:17.139+0000] {processor.py:161} INFO - Started process (PID=49720) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:29:17.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:29:17.142+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:29:17.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:29:17.150+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:29:17.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:29:17.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:29:17.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.041 seconds
[2024-07-14T07:29:47.262+0000] {processor.py:161} INFO - Started process (PID=49779) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:29:47.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:29:47.265+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:29:47.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:29:47.272+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:29:47.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:29:47.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:29:47.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.030 seconds
[2024-07-14T07:30:17.304+0000] {processor.py:161} INFO - Started process (PID=49838) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:30:17.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:30:17.307+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:30:17.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:30:17.311+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:30:17.310+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:30:17.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:30:17.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.023 seconds
[2024-07-14T07:30:47.448+0000] {processor.py:161} INFO - Started process (PID=49897) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:30:47.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:30:47.451+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:30:47.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:30:47.458+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:30:47.456+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:30:47.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:30:47.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.033 seconds
[2024-07-14T07:31:18.148+0000] {processor.py:161} INFO - Started process (PID=49956) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:31:18.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:31:18.151+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:31:18.151+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:31:18.157+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:31:18.155+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:31:18.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:31:18.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.028 seconds
[2024-07-14T07:31:48.219+0000] {processor.py:161} INFO - Started process (PID=50015) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:31:48.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:31:48.223+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:31:48.223+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:31:48.231+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:31:48.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:31:48.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:31:48.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.036 seconds
[2024-07-14T07:32:18.410+0000] {processor.py:161} INFO - Started process (PID=50074) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:32:18.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:32:18.414+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:32:18.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:32:18.421+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:32:18.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:32:18.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:32:18.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.034 seconds
[2024-07-14T07:32:48.670+0000] {processor.py:161} INFO - Started process (PID=50133) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:32:48.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:32:48.673+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:32:48.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:32:48.678+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:32:48.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:32:48.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:32:48.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.029 seconds
[2024-07-14T07:33:18.950+0000] {processor.py:161} INFO - Started process (PID=50192) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:33:18.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:33:18.953+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:33:18.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:33:18.958+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:33:18.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:33:18.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:33:18.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.031 seconds
[2024-07-14T07:33:49.035+0000] {processor.py:161} INFO - Started process (PID=50251) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:33:49.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:33:49.036+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:33:49.036+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:33:49.041+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:33:49.040+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:33:49.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:33:49.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.024 seconds
[2024-07-14T07:34:19.255+0000] {processor.py:161} INFO - Started process (PID=50316) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:34:19.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:34:19.257+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:34:19.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:34:19.262+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:34:19.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:34:19.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:34:19.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.024 seconds
[2024-07-14T07:34:50.145+0000] {processor.py:161} INFO - Started process (PID=50375) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:34:50.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:34:50.148+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:34:50.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:34:50.156+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:34:50.154+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:34:50.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:34:50.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.043 seconds
[2024-07-14T07:35:20.869+0000] {processor.py:161} INFO - Started process (PID=50434) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:35:20.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:35:20.871+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:35:20.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:35:20.877+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:35:20.876+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:35:20.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:35:20.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.031 seconds
[2024-07-14T07:35:51.649+0000] {processor.py:161} INFO - Started process (PID=50493) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:35:51.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:35:51.653+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:35:51.652+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:35:51.660+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:35:51.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:35:51.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:35:51.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.031 seconds
[2024-07-14T07:36:21.792+0000] {processor.py:161} INFO - Started process (PID=50551) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:36:21.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:36:21.796+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:36:21.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:36:21.804+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:36:21.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:36:21.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:36:21.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.046 seconds
[2024-07-14T07:36:51.992+0000] {processor.py:161} INFO - Started process (PID=50610) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:36:51.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:36:51.995+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:36:51.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:36:52.002+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:36:52.000+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:36:52.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:36:52.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.035 seconds
[2024-07-14T07:37:22.818+0000] {processor.py:161} INFO - Started process (PID=50669) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:37:22.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:37:22.821+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:37:22.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:37:22.829+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:37:22.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:37:22.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:37:22.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.033 seconds
[2024-07-14T07:37:53.642+0000] {processor.py:161} INFO - Started process (PID=50728) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:37:53.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:37:53.645+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:37:53.645+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:37:53.651+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:37:53.650+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:37:53.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:37:53.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.032 seconds
[2024-07-14T07:38:24.587+0000] {processor.py:161} INFO - Started process (PID=50787) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:38:24.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:38:24.589+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:38:24.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:38:24.596+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:38:24.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:38:24.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:38:24.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.033 seconds
[2024-07-14T07:38:55.558+0000] {processor.py:161} INFO - Started process (PID=50846) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:38:55.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:38:55.561+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:38:55.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:38:55.567+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:38:55.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:38:55.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:38:55.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.034 seconds
[2024-07-14T07:39:26.485+0000] {processor.py:161} INFO - Started process (PID=50905) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:39:26.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:39:26.488+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:39:26.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:39:26.493+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:39:26.492+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:39:26.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:39:26.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.024 seconds
[2024-07-14T07:39:56.547+0000] {processor.py:161} INFO - Started process (PID=50964) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:39:56.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:39:56.549+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:39:56.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:39:56.555+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:39:56.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:39:56.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:39:56.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.029 seconds
[2024-07-14T07:40:27.507+0000] {processor.py:161} INFO - Started process (PID=51022) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:40:27.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:40:27.510+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:40:27.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:40:27.515+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:40:27.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:40:27.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:40:27.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.027 seconds
[2024-07-14T07:40:58.443+0000] {processor.py:161} INFO - Started process (PID=51081) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:40:58.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:40:58.447+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:40:58.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:40:58.455+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:40:58.453+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:40:58.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:40:58.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.041 seconds
[2024-07-14T07:41:28.741+0000] {processor.py:161} INFO - Started process (PID=51140) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:41:28.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:41:28.745+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:41:28.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:41:28.753+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:41:28.751+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:41:28.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:41:28.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.041 seconds
[2024-07-14T07:41:58.836+0000] {processor.py:161} INFO - Started process (PID=51199) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:41:58.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:41:58.842+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:41:58.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:41:58.851+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:41:58.849+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:41:58.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:41:58.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.050 seconds
[2024-07-14T07:42:28.956+0000] {processor.py:161} INFO - Started process (PID=51258) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:42:28.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:42:28.959+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:42:28.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:42:28.963+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:42:28.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:42:28.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:42:28.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.022 seconds
[2024-07-14T07:42:59.660+0000] {processor.py:161} INFO - Started process (PID=51314) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:42:59.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:42:59.666+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:42:59.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:42:59.672+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:42:59.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:42:59.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:42:59.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.034 seconds
[2024-07-14T07:43:30.327+0000] {processor.py:161} INFO - Started process (PID=51373) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:43:30.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:43:30.333+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:43:30.333+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:43:30.341+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:43:30.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:43:30.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:43:30.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.057 seconds
[2024-07-14T07:44:00.597+0000] {processor.py:161} INFO - Started process (PID=51431) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:44:00.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:44:00.603+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:44:00.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:44:00.613+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:44:00.611+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:44:00.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:44:00.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.048 seconds
[2024-07-14T07:44:30.910+0000] {processor.py:161} INFO - Started process (PID=51490) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:44:30.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:44:30.932+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:44:30.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:44:30.942+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:44:30.940+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:44:30.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:44:30.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.068 seconds
[2024-07-14T07:45:01.398+0000] {processor.py:161} INFO - Started process (PID=51549) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:45:01.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:45:01.406+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:45:01.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:45:01.414+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:45:01.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:45:01.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:45:01.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.049 seconds
[2024-07-14T07:45:31.704+0000] {processor.py:161} INFO - Started process (PID=51608) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:45:31.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:45:31.707+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:45:31.706+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:45:31.711+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:45:31.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:45:31.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:45:31.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.036 seconds
[2024-07-14T07:46:02.371+0000] {processor.py:161} INFO - Started process (PID=51667) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:46:02.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:46:02.374+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:46:02.374+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:46:02.382+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:46:02.380+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:46:02.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:46:02.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.037 seconds
[2024-07-14T07:46:33.021+0000] {processor.py:161} INFO - Started process (PID=51726) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:46:33.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:46:33.027+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:46:33.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:46:33.038+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:46:33.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:46:33.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:46:33.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.052 seconds
[2024-07-14T07:47:03.233+0000] {processor.py:161} INFO - Started process (PID=51785) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:47:03.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:47:03.239+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:47:03.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:47:03.249+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:47:03.246+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:47:03.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:47:03.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.050 seconds
[2024-07-14T07:47:34.276+0000] {processor.py:161} INFO - Started process (PID=51844) to work on /opt/airflow/dags/airflow.py
[2024-07-14T07:47:34.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-07-14T07:47:34.283+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:47:34.282+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-07-14T07:47:34.291+0000] {logging_mixin.py:188} INFO - [2024-07-14T07:47:34.289+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from spread_functions import fetch_ticker_data, compute_spread, save_to_partitioned_directory
  File "/opt/airflow/dags/spread_functions.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-07-14T07:47:34.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-07-14T07:47:34.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.047 seconds
